### ISSUE TITLE
no such device (-19) 

### ISSUE THREAD

**Issue by Gabrycraft20** [UmbraDeorum/wlan1-mon#3]
i started the script, did everything told and wrote wlan0 and the answer is no such device (-19)

**Comment by UmbraDeorum** [comment]
I have no intention to provide support for this tool, as it is something I once created in my spare time for myself, liked it, and then decided to share. 

However, if you still face this issue, without a more extensive description I am unable to provide any advice.
You can always look up online a template for submitting GitHub issues, and then create a new one.
